---
- name: 'Include OS-specific vars'
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  no_log: true

- name: 'Ensure packages'
  ansible.builtin.package:
    name: "{{ yum_repo_packages }}"
    state: 'present'

- name: 'Include OS specific tasks'
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: 'Ensure Yum content directory'
  ansible.builtin.file:
    path: "{{ yum_repo_dir }}"
    owner: "{{ yum_repo_file_owner | default(default_yum_repo_file_owner, true) }}"
    group: "{{ yum_repo_file_group | default(default_yum_repo_file_group, true) }}"
    setype: "{{ (ansible_facts['selinux']['status'] == 'enabled') | ternary('httpd_sys_content_t', omit) }}"
    mode: '0755'
    state: 'directory'

- name: 'Remove default Apache config'
  ansible.builtin.file:
    path: "{{ yum_repo_apache_conf_dir }}/{{ conf }}"
    state: 'absent'
  loop:
    - '000-default.conf'
    - 'autoindex.conf'
    - 'ssl.conf'
    - 'userdir.conf'
    - 'welcome.conf'
  loop_control:
    loop_var: 'conf'
  notify: 'Restart apache'

- name: 'Ensure Apache config'
  ansible.builtin.template:
    src: 'repo.conf.j2'
    dest: "{{ yum_repo_apache_conf_dir }}/repo.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart apache'

- name: 'Ensure service'
  ansible.builtin.service:
    name: "{{ yum_repo_service_name }}"
    state: 'started'
    enabled: true

- name: 'Ensure repo-add script'
  ansible.builtin.template:
    src: 'repo-add.j2'
    dest: '/usr/local/bin/repo-add'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Ensure repo definition file'
  ansible.builtin.template:
    src: 'yum.repo.j2'
    dest: "{{ yum_repo_dir }}/yum.repo"
    force: false  # Don't overwrite anything placed by the user
    owner: 'root'
    group: 'root'
    mode: '0644'
