---
- name: 'Prepare image'
  hosts: 'all'
  tasks:
    - name: 'Update APT cache'
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: 'Update YUM cache'
      ansible.builtin.yum:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Ensure OS-specific packages'
      ansible.builtin.package:
        name:
          - 'firewalld'
          - 'python3-firewall'
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Ensure OS-specific services'
      ansible.builtin.service:
        name: 'firewalld'
        state: 'started'
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Ensure directory'
      ansible.builtin.file:
        path: '/etc/ssl/certs'
        mode: '0775'
        state: 'directory'

    - name: 'Generate SSL key'
      community.crypto.openssl_privatekey:
        path: '/etc/ssl/certs/server.key'
        size: 2048

    - name: 'Generate SSL cert'
      community.crypto.x509_certificate:
        path: '/etc/ssl/certs/server.crt'
        privatekey_path: '/etc/ssl/certs/server.key'
        provider: 'selfsigned'

    - name: 'Copy cert to ca'
      ansible.builtin.copy:
        src: '/etc/ssl/certs/server.crt'
        dest: '/etc/ssl/certs/ca.crt'
        mode: '0664'
        remote_src: true
